//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FleetSystemManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Costumer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Costumer()
        {
            this.RentedCars = new HashSet<RentedCars>();
        }
    
        protected string id { get; set; }
        protected string firstName { get; set; }
        protected string lastName { get; set; }
        protected string creditName { get; set; }
        protected string phone { get; set; }
        protected string mail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RentedCars> RentedCars { get; set; }
    }
}
