//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FleetSystemManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FleetMSEntities : DbContext
    {
        public FleetMSEntities()
            : base("name=FleetMSEntities")
        {
            Veichle = Set<Veichle>();
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Costumer> Costumer { get; set; }
        public virtual DbSet<RentedCars> RentedCars { get; set; }
        internal virtual DbSet<Veichle> Veichle { get; set; }
    }
}
