//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FleetSystemManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentedCars
    {
        protected string licenseNumber { get; set; }
        protected string costumerID { get; set; }
    
        public virtual Costumer Costumer { get; set; }
        public virtual Veichle Veichle { get; set; }
    }
}
