//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FleetSystemManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class Veichle
    {
        protected string name { get; set; }
        protected string licenseNumber { get; set; }
        protected int model { get; set; }
        protected int price { get; set; }
        protected int seatsNumber { get; set; }
        protected string company { get; set; }
    
        public virtual RentedCars RentedCars { get; set; }
    }
}
